spring.application.name=yuva-shakti-backend
server.port=8089
server.servlet.context-path=/api/v1

spring.datasource.url = jdbc:mysql://localhost:3306/yuva_shakti_db?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = Animesh@2005
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false

#jwt
jwt.secret=fiudsgfidsagfbviudsahgvnifedkjghioeuwtrhgvdifu
# 15 * 60 * 1000 = 15 minutes in milliseconds
jwt.access-token-expiration=900000
# 7 * 24 * 60 * 60 * 1000 = 7 days in milliseconds
jwt.refresh-token-expiration=604800000

#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6380

server.ssl.enabled=false

# All security events → separate file
logging.level.com.security=INFO
logging.file.name=logs/security.log
logging.level.org.owasp.validator.html.Policy=ERROR